### ISSUE TITLE
[BUG] - release 1.1.2  is out of sync with infinum / eightshift-libs

### ISSUE THREAD

**Issue by dmitri-ko** [infinum/eightshift-create#3]
Hi.

I'm trying to create new theme using **npx eightshift-create theme**. After some congiguration steps it says:

> To finish your setup please run one of the following command:

> wp boilerplate init-setup theme --g_frontend_libs_type='tailwind' --g_project_name='project1'

I try to run the command and get error:

**_Error: 'init-setup' is not a registered subcommand of 'boilerplate'. See 'wp help boilerplate' for available subcommands._**

**Comment by iruzevic** [comment]
Hi, yes sorry we still need to publish https://github.com/infinum/eightshift-libs/pull/415 for this all to work. It will be available in 1 hour

**Comment by iruzevic** [comment]
It is released

please run `npx eightshift-create plugin` or  `npx eightshift-create theme` and enjoy :D

**Comment by dmitri-ko** [comment]
thanx. now it's working :)
